### ISSUE TITLE
作业2的详细要求

### ISSUE THREAD

**Issue by JianSong2018** [hongxin/csmath-2019#1]
张老师，作业2的详细要求是什么呀？
1. 下载的数据集是使用哪个数据文件？是optdigits.tra吗？这个里面共有389个数字三，与PPT上说的638不一致啊
2. 对所有数字一起降维，然后显示25个数字三，这25个数字三哪里来？
3. 作图是只要把降维后的可视化显示出来就行还是也需要把那25个数字三也一并画出？

**Comment by hongxin** [comment]
Please see the update, haha
